### ISSUE TITLE
NOKNOK 的 bot 文档哪里有啊?

### ISSUE THREAD

**Issue by Liloupar** [MiniGrayGay/PaimonUID#3]
求问大佬

**Comment by MiniGrayGay** [comment]
欸嘿，文档链接：[https://bot-docs.github.io/pages/](https://bot-docs.github.io/pages/)

**Comment by MiniGrayGay** [comment]
至于Bot权限申请，可以加入 [KK官方事务所](https://link.noknok.cn/n/7AeQ5y0o) 找管理申请

**Comment by Liloupar** [comment]
@MiniGrayGay 
感谢.

>  回调地址
> 为了能够接收推送消息，首先你必须在开发者后台配置回调地址。
> 
> 当收到相应的触发消息时，开放平台会向该回调地址发送相应的 HTTP POST 请求。
> 
> 每个应用/机器人只能配置一个请求网址，该应用/机器人在所有服务器的消息都会发送到这个地址。
> 
> 接口鉴权
> 在开发者中心，在创建机器人后，我们可以得到一个 token，在请求所有的开放接口时，我们需要在 http header 的 Authorization 中加入该 token 以进行鉴权,格式为 Authorization: TOKEN。


这个开发者中心的地址有么?

**Comment by MiniGrayGay** [comment]
> 

他们开发者中心没对外，设置这些需要在官方频道找运营的同学搞

**Comment by Liloupar** [comment]
> > 
> 
> 他们开发者中心没对外，设置这些需要在官方频道找运营的同学搞

明白了, 多谢~

**Comment by MiniGrayGay** [comment]
Noknok相关的可以我加Q1042815109，我Noknok的Bot算是官方邀请入驻的，相关的也比较熟
