### ISSUE TITLE
请问微信的怎么部署？

### ISSUE THREAD

**Issue by frg666** [MiniGrayGay/PaimonUID#6]
请问微信的怎么部署？
没看明白

**Comment by MiniGrayGay** [comment]
你先装微信可爱猫，然后在
![image](https://user-images.githubusercontent.com/64829926/184641404-93b2e53c-37dd-4c48-a6ac-cd2c629a2bec.png)
消息回调地址写上你部署web服务器的地址，然后在config文件里面写入可爱猫的http地址就行，一般是保持默认的这个
![image](https://user-images.githubusercontent.com/64829926/184641678-6fdb5af6-57ad-4f7d-9b7c-b29ae9d3a133.png)
，要不加个Q1042815109进行P♂Y交易

**Comment by frg666** [comment]
成功了，号没了，（苦笑）
